# Generated by Django 3.2.16 on 2022-11-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='date',
            field=models.DateField(default='1997-08-20'),
            preserve_default=False,
        ),
    ]
